package com.hse.enums;

// type name should no longer than 60 symbols
public enum NotificationType {
    INVITATION_ANSWER_ACCEPTED,
    INVITATION_ANSWER_REJECTED,
    APPLICATION_ANSWER_ACCEPTED,
    APPLICATION_ANSWER_REJECTED,
    NEW_APPLICATION,
    NEW_INVITATION,
    NEW_CREATIVE_ASSOCIATION_INVITATION,
    CREATIVE_ASSOCIATION_INVITATION_ANSWER_ACCEPTED,
    CREATIVE_ASSOCIATION_INVITATION_ANSWER_REJECTED,
    RATE_PASSED_EVENT
}
