package com.hse.enums;

public enum NotificationType {
    INVITATION_ANSWER_ACCEPTED,
    INVITATION_ANSWER_REJECTED,
    APPLICATION_ANSWER_ACCEPTED,
    APPLICATION_ANSWER_REJECTED,
    NEW_APPLICATION,
    NEW_INVITATION,
}
